### PR TITLE
Fix missing brace, use markdown syntax for examples

### PR DESCRIPTION
**Pull request by robmcvey**

### CODE REVIEW

**Comment by robmcvey** [comment]
Sorry, just read the README about this being unmaintained (yes, the README I just edited! Doh!)

**Comment by timnolte** [comment]
@robmcvey I'm going to see if we can open up maintenance of this report. I, along with some others, forked this a a few years ago over on Google Code (https://code.google.com/p/jquery-atd-plugin/). I was in contact with the AtD folks at that time. Since Google is closing down their Code Projects platform now is as good a time as any to move on this.

**Comment by timnolte** [comment]
@robmcvey I just noticed that Google is providing a migration process to move projects there to GitHub. I'm starting the process to move it now. (https://github.com/timnolte/jquery-atd-plugin/). Once it hits there then it'll be a little better suited to work on merging these. I'll keep you posted.

**Comment by robmcvey** [comment]
:+1: Great, I'll head over there

**Pull request closed without merging**
